### ISSUE TITLE
New parameter

### ISSUE THREAD

**Issue by fikoborquez** [behindthefirewalls/Parsero#1]
Hey!,
First of all, thanks for this script, it's really usefull :)

I added a new parameter for show just HTTP 200 code status responses in my own fork of this project.

Would you like to add this new parameter?

**Comment by behindthefirewalls** [comment]
Hi fikoborquez!!

Thanks for your comment, I really appreciate it.

In this version, I want to print all the requests, not only the HTTP 200.

I am working in a new version, maybe your code could help me!!! If you want, you could share it with me.

**Comment by behindthefirewalls** [comment]
Thanks for your time. I've just merged your code.

**Comment by fikoborquez** [comment]
I'd like to help with the new version, just tell me what to do.

**Comment by behindthefirewalls** [comment]
Great!!! Now I'm finishing the last version. If you want contact me at the bottom of my blog: http://www.behindthefirewalls.com/ and give me your e-mail. We could keep talking about new Parsero's features.
